version: "3.9"

services:
  telegrambot:
    build: .
    container_name: telegrambot_gpu
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/app
    command: ["uvicorn", "telegrambot:app", "--host", "0.0.0.0", "--port", "8000"]
